trigger:
  branches:
    include: 
    - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: packageBuild
    displayName: Package Build
    steps:

    - task: NodeTool@0
      displayName: Install Node
      inputs:
        versionSpec: 20.x
        displayName: Install Node.js

    - script: |
        if [ -f extensions.csproj ]
        then
          dotnet build extensions.csproj --runtime ubuntu.24.04-x64 --output ./bin
        fi
      displayName: Build extensions

    - task: AzureCLI@2
      displayName: Prepare Database Firewall
      name: addRule
      condition: succeeded()
      inputs:
        azureSubscription: PasseiOAB
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          PUB_IP=$(curl https://ipecho.net/plain ; echo)
          az mysql flexible-server firewall-rule create \
          --name $(echo $(DATABASE_URL) | cut -d "." -f1) \
          --resource-group $(RESOURCE_GROUP) \
          --end-ip-address $PUB_IP \
          --rule-name "tempRule" \
          --start-ip-address $PUB_IP
        env:
        RESOURCE_GROUP: $(RESOURCE_GROUP)

    - script: |
        npx --yes husky
        npm build
        npm start
      displayName: Prepare binaries
      name: nodeBuild

